#!/bin/bash 

message=""

if [[ $# -gt 2 ]];
then 
	printf "%s\n" "Error to many arguments"
	exit 1 
fi 

if [[ $# -eq 2 ]];then

	if [[ $1 = '-v' ]];then 
		printf "%s :\n\t%s" "Message" "$2" || printf "ERR: Unable to show message" 
		exit 
	fi
fi 





